services:
  bot:
    build: .
    image: bitbotterich
    volumes:
        - bitbotterich:/data
volumes:
    bitbotterich:
        driver: local
        driver_opts:
          type: none
          device: /data/bitbotterich
          o: bind