services:
  bot:
    build: .
    image: bitbotterich
    volumes:
        - type: volume
          source: bitbotterichdata
          target: /data
volumes:
    bitbotterichdata:
        driver: local
        driver_opts:
          type: none
          device: /data/bitbotterichdata
          o: bind